# 모델 resnet34, resnet50
model_name : "resnet18"

num_actions :
num_emotions : 
num_situations :

# 모델 저장 경로
save_path: "./saved_models"
best_model_path: ""       

# 데이터 경로 설정
data_dir: "../data"                
train_file: ".json"                                   
val_file: ".json"          
test_file: ".json"  

batch_size: 8       # 데이터 작고, 클래스 불균형 → 작은 배치 사이즈로 더 자주 업데이트
epochs: 50
learning_rate: 3e-5
seed: 42
device: "cuda" 

# wandb 설정
wandb_project: "PetBabel_project"