# 모델 resnet34, resnet50
model_name : "resnet18"

# 모델 저장 경로
save_path: "./saved_models_3rd"
best_model_path: ""       
test_image_path : ""    

# 데이터 경로 설정
data:
  train_csv: ../data/train_1st.csv
  val_csv: ../data/val_1st.csv
  test_csv: ../data/test_1st.csv
  root_dir: "../data/CAT_image"   # 프레임 이미지 저장 경로 (예: ./frames/video_name/000001.jpg ...)

batch_size: 8       # 데이터 작고, 클래스 불균형 → 작은 배치 사이즈로 더 자주 업데이트
epochs: 30
learning_rate: 1e-3       # 1e-3~1e-4   3e-5
seed: 42
device: "cuda:1" 

# wandb 설정
wandb_project: "PetBabel_project"


label_names:
  action:                     # 12개
    - 걷거나 달리는 동작
    - 그루밍하는 동작
    - 꼬리를 흔드는 동작
    - 납작 엎드리는 동작
    - 머리를 들이대는 동작
    - 발을 숨기고 웅크리고 앉는 동작
    - 배를 보여주는 동작
    - 앞발로 꾹꾹 누르는 동작
    - 앞발을 뻗어 휘적거리는 동작
    - 옆으로 눕는 동작
    - 좌우로 뒹구는 동작
    - 허리를 아치로 세우는 동작

  situation:        # 22개
    - 공격성_기타
    - 공격성_먹을것, 장난감이 앞에 있을 때
    - 불안/슬픔_기타
    - 불안/슬픔_낯선 소리가 나거나 낯선 사람을 봤을 때
    - 편안/안정_기타
    - 편안/안정_다른 사람이나 동물을 만났을 때
    - 편안/안정_먹을것, 장난감이 앞에 있을 때
    - 편안/안정_보호자가 집에 돌아왔을 때
    - 편안/안정_빗질/발톱깍기/목욕 등 위생관리를 할 때
    - 편안/안정_산책 준비 또는 산책중일 때
    - 편안/안정_산책이나 노즈워크 중
    - 편안/안정_싫어하는 부위를 만질 때
    - 편안/안정_잠들기 전이나 같이 누워있을 때
    - 편안/안정_편안히 쓰다듬어 줄 때
    - 편안/안정_휴식시간, 자신만의 공간에 들어갔을 때(캔넬, 소파 침대 밑 등)
    - 행복/즐거움_기타
    - 행복/즐거움_먹을것, 장난감이 앞에 있을 때
    - 행복/즐거움_보호자가 집에 돌아왔을 때
    - 행복/즐거움_산책 준비 또는 산책중일 때
    - 화남/불쾌_기타
    - 화남/불쾌_먹을것, 장난감이 앞에 있을 때
    - 화남/불쾌_싫어하는 부위를 만질 때
