# 모델 resnet34, resnet50
model_name : "resnet50"

# 모델 저장 경로
save_path: "./saved_models"
best_model_path: "0615_2231_epoch7_valLoss0.2958_macro_f1_0.9681.pth"       

# 데이터 경로 설정
data:
  train_csv: ../data/train.csv
  val_csv: ../data/val.csv
  test_csv: ../data/test.csv

batch_size: 16       # 데이터 작고, 클래스 불균형 → 작은 배치 사이즈로 더 자주 업데이트
epochs: 30
learning_rate: 5e-5       # 1e-3~1e-4   3e-5
seed: 42
device: "cuda:2" 

# wandb 설정
wandb_project: "PetBabel_project"


label_names:
  action:
    - 허리를 아치로 세우는 동작
    - 걷거나 달리는 동작
    - 머리를 들이대는 동작
    - 발을 숨기고 웅크리고 앉는 동작
    - 좌우로 뒹구는 동작
    - 납작 엎드리는 동작
    - 그루밍하는 동작
    - 배를 보여주는 동작
    - 허리를 아치로 세움
    - 앞발로 꾹꾹 누르는 동작
    - 옆으로 눕는 동작
    - 꼬리를 흔드는 동작
    - 앞발을 뻗어 휘적거리는 동작

  emotion:
    - 화남/불쾌
    - 편안/안정
    - 행복/즐거움
    - 공격성
    - 공포
    - 불안/슬픔

  situation:
    - 보호자와 떨어질 때/혼자 남겨지거나 낯선장소에 있을 때
    - 밥그릇, 장난감과 같은 소유물을 만질 때
    - 산책이나 노즈워크 중
    - 기타
    - 산책 준비 또는 산책중일 때
    - 다른 동물을 보거나 낯선 사람을 만날 때 산책 나왔을 때
    - 다른 사람이나 동물을 만났을 때
    - 낯선 장소에 있거나 낯선 소리가 날 때
    - 먹을것, 장난감이 앞에 있을 때
    - 싫어하는 부위를 만질 때
    - 편안히 쓰다듬어 줄 때
    - 보호자가 집에 돌아왔을 때
    - 휴식시간, 자신만의 공간에 들어갔을 때(캔넬, 소파 침대 밑 등)
    - 잠들기 전이나 같이 누워있을 때
    - 빗질/발톱깍기/목욕 등 위생관리를 할 때
    - 낯선 소리가 나거나 낯선 사람을 봤을 때
    - 낯선 소리가 났을 때
